-- MySQL Script generated by MySQL Workbench
-- Sun Apr  9 12:55:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- ---------------------Account--------------------------------
-- Schema testdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `testdb` ;

-- -----------------------------------------------------
-- Schema testdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testdb` DEFAULT CHARACTER SET latin1 ;
USE `testdb` ;

-- -----------------------------------------------------
-- Table `testdb`.`Standard-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Standard-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Standard-ani` (
  `TypeID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `MinWeight` INT NOT NULL,
  `MaxWeight` INT NOT NULL,
  `MinLength` INT NOT NULL,
  `MaxLength` INT NOT NULL,
  `MinTemp` INT NOT NULL,
  `MaxTemp` INT NOT NULL,
  `MinRespire` INT NOT NULL,
  `MaxRespire` INT NOT NULL,
  `MinHeartbeat` INT NOT NULL,
  `MaxHeartbeat` INT NOT NULL,
  `MinBloodpressure` INT NOT NULL,
  `MaxBloodpressure` INT NOT NULL,
  `RunningSpeed` INT NOT NULL,
  PRIMARY KEY (`TypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Staff` (
  `StaffID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StaffID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Animal-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Animal-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Animal-ani` (
  `AnimalID` INT NOT NULL AUTO_INCREMENT,
  `TypeID` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Age` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AnimalID`),
  INDEX `fk_Animal-ani_Standard-ani1_idx` (`TypeID` ASC),
  CONSTRAINT `fk_Animal-ani_Standard-ani1`
    FOREIGN KEY (`TypeID`)
    REFERENCES `testdb`.`Standard-ani` (`TypeID`)
 --   ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Collar-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Collar-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Collar-ani` (
  `CollarID` INT NOT NULL AUTO_INCREMENT,
  `ActivateDate` DATE NOT NULL,
  `AnimalID` INT NOT NULL,
  `ProductInfo` VARCHAR(45) NOT NULL,
  `StaffID` INT NOT NULL,
  PRIMARY KEY (`CollarID`),
  INDEX `fk_Collar-ani_Animal-ani1_idx` (`AnimalID` ASC),
  CONSTRAINT `fk_Collar-ani_Animal-ani1`
    FOREIGN KEY (`AnimalID`)
    REFERENCES `testdb`.`Animal-ani` (`AnimalID`)
 --    ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Sensor-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Sensor-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Sensor-ani` (
  `SensorID` INT NOT NULL AUTO_INCREMENT,
  `AnimalID` INT NOT NULL,
  `ActivateDate` DATE NOT NULL,
  PRIMARY KEY (`SensorID`),
  INDEX `fk_Sensor-ani_Animal-ani1_idx` (`AnimalID` ASC),
  CONSTRAINT `fk_Sensor-ani_Animal-ani1`
    FOREIGN KEY (`AnimalID`)
    REFERENCES `testdb`.`Animal-ani` (`AnimalID`)
  --   ON DELETE NO ACTION
 --   ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`CollarData-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`CollarData-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`CollarData-ani` (
  `CollarDataID` INT NOT NULL AUTO_INCREMENT,
  `RecordDate` DATE NOT NULL,
  `HeartBeat` INT NOT NULL,
  `Respire` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Power` VARCHAR(45) NULL,
  `Connection` VARCHAR(45) NULL,
  `RecycleDate` DATE NULL,
  `CollarID` INT NOT NULL,
  `Temperature` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CollarDataID`, `RecordDate`),
  INDEX `fk_CollarData-ani_Collar-ani1_idx` (`CollarID` ASC),
  CONSTRAINT `fk_CollarData-ani_Collar-ani1`
    FOREIGN KEY (`CollarID`)
    REFERENCES `testdb`.`Collar-ani` (`CollarID`)
 --   ON DELETE NO ACTION
 --   ON UPDATE NO ACTION
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Analyst`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Analyst` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Analyst` (
  `AnalystID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AnalystID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`SensorData-ani`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`SensorData-ani` ;

CREATE TABLE IF NOT EXISTS `testdb`.`SensorData-ani` (
  `SensorDataID` INT NOT NULL AUTO_INCREMENT,
  `RecordDate` DATE NOT NULL,
  `Bloodpressure` INT NOT NULL,
  `Power` INT NULL,
  `Connection` INT NULL,
  `SensorID` INT NOT NULL,
  `Bioelectricity` INT NOT NULL,
  `PH` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SensorDataID`),
  INDEX `fk_SensorData-ani_Sensor-ani1_idx` (`SensorID` ASC),
  CONSTRAINT `fk_SensorData-ani_Sensor-ani1`
    FOREIGN KEY (`SensorID`)
    REFERENCES `testdb`.`Sensor-ani` (`SensorID`)
  --   ON DELETE NO ACTION
  --   ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Donor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Donor` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Donor` (
  `DonationID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `AnimalID` INT NOT NULL,
  `Amount` INT NOT NULL,
  PRIMARY KEY (`DonationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Donation`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `testdb`.`Donation` ;
-- 
-- CREATE TABLE IF NOT EXISTS `testdb`.`Donation` (
--   `DonationID` INT NOT NULL AUTO_INCREMENT,
--   `DonorID` INT NOT NULL,
--   `AnimalID` INT NOT NULL,
--   `Amount` INT NOT NULL,
--   PRIMARY KEY (`DonationID`),
--   INDEX `fk_Donation_Donor1_idx` (`DonorID` ASC),
--   CONSTRAINT `fk_Donation_Donor1`
--     FOREIGN KEY (`DonorID`)
--     REFERENCES `testdb`.`Donor` (`DonorID`)
--   --   ON DELETE NO ACTION
--   --   ON UPDATE NO ACTION
--   )
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Vet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Vet` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Vet` (
  `VetID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`VetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Treatment` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Treatment` (
  `TreatmentID` INT NOT NULL AUTO_INCREMENT,
  `VetID` INT NOT NULL,
  `AnimalID` INT NOT NULL,
  `TreatmentRecord` VARCHAR(45) NOT NULL,
  `TreatmentDate` DATE NOT NULL,
  PRIMARY KEY (`TreatmentID`),
  INDEX `fk_Treatment_Vet1_idx` (`VetID` ASC),
  CONSTRAINT `fk_Treatment_Vet1`
    FOREIGN KEY (`VetID`)
    REFERENCES `testdb`.`Vet` (`VetID`)
  --   ON DELETE NO ACTION
  --   ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Manager` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Manager` (
  `ManagerID` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ManagerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Volunteer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Volunteer` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Volunteer` (
  `ApplicationID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `Resume` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ApplicationID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Account` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Account` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Job` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;




-- -----------------------------------------------------
-- Table `testdb`.`Standard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Standard` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Standard` (
  `TypeID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `MinWeight` INT NOT NULL,
  `MaxWeight` INT NOT NULL,
  `MinLength` INT NOT NULL,
  `MaxLength` INT NOT NULL,
  `MinTemp` INT NOT NULL,
  `MaxTemp` INT NOT NULL,
  `MinRespire` INT NOT NULL,
  `MaxRespire` INT NOT NULL,
  `MinHeartbeat` INT NOT NULL,
  `MaxHeartbeat` INT NOT NULL,
  `MinBloodpressure` INT NOT NULL,
  `MaxBloodpressure` INT NOT NULL,
  `RunningSpeed` INT NOT NULL,
  PRIMARY KEY (`TypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Animal` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Animal` (
  `AnimalID` INT NOT NULL AUTO_INCREMENT,
  `TypeID` INT NOT NULL,
  `Status` INT NOT NULL,
  `Age` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AnimalID`),
  INDEX `fk_Animal_Standard1_idx` (`TypeID` ASC),
  CONSTRAINT `fk_Animal_Standard1`
    FOREIGN KEY (`TypeID`)
    REFERENCES `testdb`.`Standard` (`TypeID`)
  --   ON DELETE NO ACTION
  --   ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`SickAnimal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`SickAnimal` ;

CREATE TABLE IF NOT EXISTS `testdb`.`SickAnimal` (
  `SickID` INT NOT NULL AUTO_INCREMENT,
  `AnimalID` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `Status` INT NOT NULL,
  PRIMARY KEY (`SickID`),
  INDEX `fk_SickAnimal_Animal1_idx` (`AnimalID` ASC),
  CONSTRAINT `fk_SickAnimal_Animal1`
    FOREIGN KEY (`AnimalID`)
    REFERENCES `testdb`.`Animal` (`AnimalID`)
 --    ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Collar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Collar` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Collar` (
  `CollarID` INT NOT NULL AUTO_INCREMENT,
  `ActivateDate` DATE NOT NULL,
  `AnimalID` INT NOT NULL,
  `ProductInfo` VARCHAR(45) NOT NULL,
  `StaffID` int(11) NOT NULL,
   PRIMARY KEY (`CollarID`),
  INDEX `fk_Collar_Animal1_idx` (`AnimalID` ASC),
  INDEX `fk_Collar_Staff1_idx` (`StaffID` ASC),
  CONSTRAINT `fk_Collar_Animal1`
    FOREIGN KEY (`AnimalID`)
    REFERENCES `testdb`.`Animal` (`AnimalID`),
--    ON DELETE NO ACTION
 --   ON UPDATE NO ACTION,
  CONSTRAINT `fk_Collar_Staff1`
    FOREIGN KEY (`StaffID`)
    REFERENCES `testdb`.`Staff` (`StaffID`)
 --   ON DELETE NO ACTION
  --  ON UPDATE NO ACTION
 
 
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`CollarData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`CollarData` ;

CREATE TABLE IF NOT EXISTS `testdb`.`CollarData` (
  `CollarDataID` INT NOT NULL AUTO_INCREMENT,
  `RecordDate` DATE NOT NULL,
  `HeartBeat` INT NOT NULL,
  `Respire` INT NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `CollarID` INT NOT NULL,
  `Temperature` VARCHAR(45) NULL,
  PRIMARY KEY (`CollarDataID`),
  INDEX `fk_CollarData_Collar1_idx` (`CollarID` ASC),
  CONSTRAINT `fk_CollarData_Collar1`
    FOREIGN KEY (`CollarID`)
    REFERENCES `testdb`.`Collar` (`CollarID`)
 --    ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Sensor` (
  `SensorID` INT NOT NULL AUTO_INCREMENT,
  `ActivateDate` DATE NOT NULL,
  `AnimalID` INT NOT NULL,
  `ProductInfo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SensorID`),
  INDEX `fk_Sensor_Animal1_idx` (`AnimalID` ASC),
  CONSTRAINT `fk_Sensor_Animal1`
    FOREIGN KEY (`AnimalID`)
    REFERENCES `testdb`.`Animal` (`AnimalID`)
 --    ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`SensorData`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`SensorData` ;

CREATE TABLE IF NOT EXISTS `testdb`.`SensorData` (
  `SensorDataID` INT NOT NULL AUTO_INCREMENT,
  `RecordDate` DATE NOT NULL,
  `Bloodpressure` INT NOT NULL,
  `SensorID` INT NOT NULL,
  `Bioelectricity` INT NOT NULL,
  `PH` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SensorDataID`),
  INDEX `fk_SensorData_Sensor1_idx` (`SensorID` ASC),
  CONSTRAINT `fk_SensorData_Sensor1`
    FOREIGN KEY (`SensorID`)
    REFERENCES `testdb`.`Sensor` (`SensorID`)
--     ON DELETE NO ACTION
 --    ON UPDATE NO ACTION
 )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `testdb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `testdb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `testdb`.`Employee` (
  `ID` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



drop user if  exists 'Manager'@'localhost';
drop user if  exists 'Analyst'@'localhost';
drop user if exists 'Vet'@'localhost';
drop user if exists 'Staff'@'localhost';

CREATE USER 'Manager'@'localhost'  IDENTIFIED BY 'mng';
CREATE USER 'Analyst'@'localhost'  IDENTIFIED BY 'analyst';
CREATE USER 'Vet'@'localhost'  IDENTIFIED BY 'vet';
CREATE USER 'Staff'@'localhost'  IDENTIFIED BY 'tech';


revoke all privileges, grant option from 'Manager'@'localhost' ;
revoke all privileges, grant option from 'Analyst'@'localhost' ;
revoke all privileges, grant option from 'Vet'@'localhost' ;
revoke all privileges, grant option from 'Staff'@'localhost' ;


GRANT ALL ON testdb.* TO 'Manager'@'localhost' ;


GRANT SELECT,UPDATE ON testdb.Account TO 'Manager'@'localhost';
GRANT SELECT ON testdb.CollarData TO 'Analyst'@'localhost';
GRANT SELECT ON testdb.SensorData TO 'Analyst'@'localhost';
GRANT SELECT, UPDATE (Status) ON testdb.Animal TO 'Vet'@'localhost';
GRANT SELECT,UPDATE(AnimalID,TypeID,Name,Age) ON testdb.Animal TO 'Manager'@'localhost';
GRANT SELECT,UPDATE(CollarID,ActivateDate,StaffID) ON testdb.Collar TO 'Staff'@'localhost';
GRANT SELECT,UPDATE(AnimalID,TreatmentRecord,TreatmentDate) ON testdb.Treatment TO 'Vet'@'localhost';




